#!/usr/bin/env bash
## AUTOGENERATED, DO NOT EDIT THIS FILE DIRECTLY.
set -euo pipefail

BASE_PATH=$(dirname "$0")
PARENT_PATH=$(dirname "$BASE_PATH")

echo "[{{ .name }}] down..."

{{ .downScript }}

echo "[{{ .name }}] down done."
