#!/usr/bin/env bash
## AUTOGENERATED, DO NOT EDIT THIS FILE DIRECTLY.
set -euo pipefail

BASE_PATH=$(dirname "$0")
PARENT_PATH=$(dirname "$BASE_PATH")

echo "[{{ .name }}] ansible-playbook up..."

EXTRA_VARS_FLAG=""
{{ if .extraVars -}}
EXTRA_VARS_FLAG="--extra-vars '{{ .extraVars }}'"
{{- end }}

ansible-playbook \
  -i "${PARENT_PATH}/inventory.ini" \
  ${EXTRA_VARS_FLAG} \
  "${PARENT_PATH}/playbook-up.yml"

echo "[{{ .name }}] ansible-playbook up done."
