#!/usr/bin/env bash
## AUTOGENERATED, DO NOT EDIT THIS FILE DIRECTLY.
## Verbe url — Retourne l'URL d'accès de {{ .title }}
set -euo pipefail

{{ if .accessUrl -}}
# Résoudre les variables d'environnement dans l'URL
eval echo "{{ .accessUrl }}"
{{- else -}}
echo "Aucune URL d'accès définie pour {{ .name }}" >&2
exit 1
{{- end }}
